spring:
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: com.nari.parent.productservice.util.HibernatePhysicalNamingNamingStrategy
    show-sql: false
